=== IgorKukhtin/DSD/DOC/Вспомогательные/EDI/!!!СТРУКТУРА!!!/J1201009.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>ПОДАТКОВА НАКЛАДНА 
		(ЗАТВЕРДЖЕНО Наказ Міністерства фінансів України 31 грудня 2015 року № 1307 (у редакції наказу Міністерства фінансів України 23 лютого 2017 року №  276))
		</xs:documentation>
	</xs:annotation>
	<xs:include schemaLocation="common_types.xsd"/>
	<xs:element name="DECLAR" type="DeclarContent"/>
	<xs:complexType name="DeclarContent">
		<xs:sequence>
			<xs:element name="DECLARHEAD" type="DHead"/>
			<xs:element name="DECLARBODY" type="DBody">
				<xs:unique name="URXXXXG3S">
					<xs:selector xpath="RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG4">
					<xs:selector xpath="RXXXXG4"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG32">
					<xs:selector xpath="RXXXXG32"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG33">
					<xs:selector xpath="RXXXXG33"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG4S">
					<xs:selector xpath="RXXXXG4S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG105_2S">
					<xs:selector xpath="RXXXXG105_2S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG5">
					<xs:selector xpath="RXXXXG5"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG6">
					<xs:selector xpath="RXXXXG6"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG008">
					<xs:selector xpath="RXXXXG008"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG009">
					<xs:selector xpath="RXXXXG009"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG010">
					<xs:selector xpath="RXXXXG010"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="URXXXXG011">
					<xs:selector xpath="RXXXXG011"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DHead">
		<xs:sequence>
			<xs:element name="TIN" type="DGLong"/>
			<xs:element name="C_DOC" type="xs:string" fixed="J12"/>
			<xs:element name="C_DOC_SUB" type="xs:string" fixed="010"/>
			<xs:element name="C_DOC_VER" type="xs:string" fixed="9"/>
			<xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger"/>
			<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger"/>
			<xs:element name="C_REG" type="DGsti"/>
			<xs:element name="C_RAJ" type="DGsti"/>
			<xs:element name="PERIOD_MONTH" type="DGMonth"/>
			<xs:element name="PERIOD_TYPE" type="DGPType"/>
			<xs:element name="PERIOD_YEAR" type="DGYear"/>
			<xs:element name="C_STI_ORIG" type="DGc_dpi"/>
			<xs:element name="C_DOC_STAN" type="DGSTAN"/>
			<xs:element name="LINKED_DOCS" nillable="true" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="DOC" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="C_DOC" type="DGC_DOC"/>
									<xs:element name="C_DOC_SUB" type="DGC_DOC_SUB"/>
									<xs:element name="C_DOC_VER" type="DGC_DOC_VER"/>
									<xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger"/>
									<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger"/>
									<xs:element name="C_DOC_STAN" type="DGSTAN"/>
									<xs:element name="FILENAME" type="DGFilename"/>
								</xs:sequence>
								<xs:attribute name="NUM" type="xs:nonNegativeInteger"/>
								<xs:attribute name="TYPE" type="DGTypeLinkDoc"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
				<xs:unique name="UH_DOC_NUM">
					<xs:selector xpath="DOC"/>
					<xs:field xpath="@NUM"/>
				</xs:unique>
			</xs:element>
			<xs:element name="D_FILL" type="DGDate"/>
			<xs:element name="SOFTWARE" type="xs:string" nillable="true" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DBody">
		<xs:sequence>
			<!--HEAD-->
			<xs:element name="H03" type="DGchk" nillable="true" minOccurs="0"/>
			<xs:element name="R03G10S" type="xs:string" nillable="true" minOccurs="0"/>
			<xs:element name="HORIG1" type="DGchk" nillable="true" minOccurs="0"/>
			<xs:element name="HTYPR" type="DGPNtypr" nillable="true" minOccurs="0"/>
			<xs:element name="HFILL" type="DGDate"/>
			<xs:element name="HNUM" type="DGI7nom"/>
			<xs:element name="HNUM1" type="DGspecNom" nillable="true" minOccurs="0"/>
			<xs:element name="HNAMESEL" type="DGHNAME"/>
			<xs:element name="HNAMEBUY" type="DGHNAME"/>
			<xs:element name="HKSEL" type="DGHNPDV"/>
			<xs:element name="HNUM2" type="DGI4nom" nillable="true" minOccurs="0"/>
			<xs:element name="HKBUY" type="DGHIPN0"/>
			<xs:element name="HFBUY" type="DGI4nom" nillable="true" minOccurs="0"/>
			<!--BODY-->
			<xs:element name="R04G11" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R03G11" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R03G7" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R03G109" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R01G7" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R01G109" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R01G9" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R01G8" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R01G10" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<xs:element name="R02G11" type="DGdecimal2_P" nillable="true" minOccurs="0"/>
			<!--TABLE №1-->
			<xs:element name="RXXXXG3S" type="StrColumn" nillable="true" maxOccurs="9999"/>
			<xs:element name="RXXXXG4" type="UKTZEDColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG32" type="ChkColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG33" type="DKPPColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG4S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG105_2S" type="DGI4lzColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG5" type="Decimal6Column_R" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG6" type="Decimal12Column_R" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG008" type="DGI3nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG009" type="CodPilgColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG010" type="Decimal2Column_P" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="RXXXXG011" type="DGI3nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №1-->
			<!--FOOTER-->
			<xs:element name="HBOS" type="DGHBOS"/>
			<xs:element name="HKBOS" type="DGLong"/>
			<xs:element name="R003G10S" type="xs:string" nillable="true" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== IgorKukhtin/DSD/DOC/ТЗ-Алан/IFIN_NALOG_04650024447183J1201009100100000210720170465.xml
<?xml version="1.0" encoding="windows-1251"?>
<DECLAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="J1201009.xsd">
  <DECLARHEAD>
    <TIN>24447183</TIN>
    <C_DOC>J12</C_DOC>
    <C_DOC_SUB>010</C_DOC_SUB>
    <C_DOC_VER>9</C_DOC_VER>
    <C_DOC_TYPE>00</C_DOC_TYPE>
    <C_DOC_CNT>1000002</C_DOC_CNT>
    <C_REG>04</C_REG>
    <C_RAJ>65</C_RAJ>
    <PERIOD_MONTH>7</PERIOD_MONTH>
    <PERIOD_TYPE>1</PERIOD_TYPE>
    <PERIOD_YEAR>2017</PERIOD_YEAR>
    <C_STI_ORIG>0465</C_STI_ORIG>
    <C_DOC_STAN>1</C_DOC_STAN>
    <LINKED_DOCS xsi:nil="true" />
    <D_FILL>06072017</D_FILL>
    <SOFTWARE>iFin</SOFTWARE>
  </DECLARHEAD>
  <DECLARBODY>
    <H03 xsi:nil="true" />
    <R03G10S xsi:nil="true" />
    <HORIG1 xsi:nil="true" />
    <HTYPR xsi:nil="true" />
    <HFILL>13072017</HFILL>
    <HNUM>1</HNUM>
    <HNUM1 xsi:nil="true" />
    <HNAMESEL>Товариство з обмеженою відповідальністю "АЛАН"</HNAMESEL>
    <HNAMEBUY>тов мак</HNAMEBUY>
    <HKSEL>244471804626</HKSEL>
    <HNUM2 xsi:nil="true" />
    <HKBUY>123456789</HKBUY>
    <HFBUY xsi:nil="true" />
    <R04G11>2.40</R04G11>
    <R03G11>0.40</R03G11>
    <R03G7>0.40</R03G7>
    <R03G109 xsi:nil="true" />
    <R01G7>2.00</R01G7>
    <R01G109 xsi:nil="true" />
    <R01G9 xsi:nil="true" />
    <R01G8 xsi:nil="true" />
    <R01G10 xsi:nil="true" />
    <R02G11 xsi:nil="true" />
    <RXXXXG3S ROWNUM="1">прплорлдодлджлжд</RXXXXG3S>
    <RXXXXG4 ROWNUM="1" xsi:nil="true" />
    <RXXXXG32 ROWNUM="1" xsi:nil="true" />
    <RXXXXG33 ROWNUM="1" xsi:nil="true" />
    <RXXXXG4S ROWNUM="1">шт</RXXXXG4S>
    <RXXXXG105_2S ROWNUM="1">2009</RXXXXG105_2S>
    <RXXXXG5 ROWNUM="1">1.000000000000</RXXXXG5>
    <RXXXXG6 ROWNUM="1">2.000000000000</RXXXXG6>
    <RXXXXG008 ROWNUM="1">20</RXXXXG008>
    <RXXXXG009 ROWNUM="1" xsi:nil="true" />
    <RXXXXG010 ROWNUM="1">2.00</RXXXXG010>
    <RXXXXG011 ROWNUM="1" xsi:nil="true" />
    <HBOS>В. М. Крихта</HBOS>
    <HKBOS>2071800356</HKBOS>
    <R003G10S xsi:nil="true" />
  </DECLARBODY>
</DECLAR>
